import type { Metadata } from "next";

import { Inter } from "next/font/google";
import "./globals.css";
import Web3Modal from "../web3provider/Web3Modal";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "StakDTX",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Web3Modal>
        <body className={inter.className}>{children}</body>
      </Web3Modal>
    </html>
  );
}
